### PR TITLE
Updated Senza YAML & Readme

### PR DESCRIPTION
**Pull request by jhhannon**
Updated Senza with application_id, mint bucket access and changed readme accordingly.

### CODE REVIEW

**Comment by drummerwolli** [comment]
you don't need this parameters to start the appliance if you use the OS registry version.

you can find out the latest version with this: 

```
curl -s https://registry.opensource.zalan.do/teams/saiki/artifacts/buku/tags | jq "sort_by(.created)"
```

we should probably add the hint to the OS version to the readme @CyberDem0n  ...

**Comment by chris-zen** [comment]
@drummerwolli it is not clear to me why being able to customise the application id is not relevant and accepted, as every team would be interested in deploying it with a different stack name than the default one (exhibitor).

Would you accept this PR if the MintBucket stuff was removed from it?

**Comment by drummerwolli** [comment]
hey @chris-zen 
- i'm not the maintainer of this project, just stating my thoughts ;-)
- i think everyone can just create its own yaml file locally and include the application_id if needed. the provided one is just a template, which shows the essential parameters. i don't see a strong need to include this in the repo, but thats just my opionion. please don't see this as a blocker ...

**Comment by chris-zen** [comment]
@drummerwolli thanks for the response, I'd love to hear from the maintainers too.
Not having senza templates generic enough just promotes the copy-paste culture where every team has its own customised copy of the template that will end being out of date sooner than later, and make tracking the changes more difficult. Just my thoughts.

**Comment by drummerwolli** [comment]
@chris-zen i changed my mind, already created a PR: https://github.com/zalando/exhibitor-appliance/pull/22 ...

**Comment by chris-zen** [comment]
@drummerwolli, thanks, really appreciated. I commented on #22

**Pull request closed without merging**
