### PR TITLE
scalyr inside docker for zookeeper.out

### PR DESCRIPTION
**Pull request by drummerwolli**

### CODE REVIEW

**Comment by CyberDem0n** [comment]
I like the idea of pushing zookeeper logs to scalyr, but I don't understand why do you want to install scalyr into docker...

1) We already have scalyr configured on EC2 instance.
2) What if one day we will decide to switch from scalyr to some other facility?

So instead of installing scalyr into docker it's much easier and faster just "tailf zookeeer.out". This way it will appear in a application.log and later would be imported by scalyr automatically. 

Something like this:
https://github.com/zalando/exhibitor-appliance/pull/10/files

**Comment by valgog** [comment]
@drummerwolli have a look on that black magic solution for scalyr and logentries integration from @CyberDem0n

**Comment by drummerwolli** [comment]
i also thought about just tailing the logs into the application logs. this would also make the hosts distinguishable, but i didn't like the idea to scram all kind of different logs together into one log in scalyr. i thought it would be nicer to identify which logs come from which service. imagine having more than two services/logs in one container ...

but sure, the other thing would work too, and is log provider independet, agreed.

**Comment by valgog** [comment]
Yes, this is nice discussion and very valid topics about the ability to differentiate the logs from different systems.

Maybe there is some nicer way to do it, like using syslogd or something like this to push logs to, that will be delivered to the EC2 level configured logging collector?

**Comment by drummerwolli** [comment]
internally discussed to rather use tail -f, done with https://github.com/zalando/exhibitor-appliance/commit/c2cb8d8ca104f8e355f7274af4618fb61c4009c5 ... i will close this ...

**Pull request closed without merging**
